# Generated by Django 5.1.7 on 2025-04-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
